---

# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center

- name: Set hot screen corners.
  osx_defaults:
    domain: com.apple.dock
    key: "{{ item.name }}"
    type: int
    value: "{{ item.value }}"
  with_items:
    - name: wvous-tr-corner
      value: 4
    - name: wvous-tr-modifier
      value: 0
    - name: wvous-bl-corner
      value: 5
    - name: wvous-bl-modifier
      value: 0
    - name: wvous-br-corner
      value: 3
    - name: wvous-br-modifier
      value: 0
  notify: Restart Dock
