---

- name: Disable Dashboard.
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true

- name: Disable auto correct.
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: Disable smart quotes.
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false

- name: Disable smart dashes.
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false

- name: Use F keys as standard function keys.
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: int
    value: 1
