---

#echo "$MY_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee --append /etc/sudoers

- name: Mac Dev Playbook
  hosts: localhost
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['packages, homebrew']

    - role: packages
      tags: ['packages, extra']

    - name: yadm
      tags: [config, dotfiles]

    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

    - name: macos
      tags: [config, macos]

  tasks:
    - name: Upgrade all homebrew packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      tags: [always]
      when: upgrade_all_homebrew_packages
