---

#echo "$MY_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee --append /etc/sudoers

- hosts: all
  connection: local
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: [packages, apps]

    - name: yadm
      tags: [config, dotfiles]

    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: apps

    - name: macos
      tags: [config, macos]

  tasks:
    - import_tasks: tasks/extra-packages.yml
      tags: [packages, extra-packages]
    - import_tasks: tasks/shell.yml
      tags: [config, shell]
    - import_tasks: tasks/screensaver.yml
      tags: config
    - import_tasks: tasks/iterm2.yml
      tags: [config, iterm2]
    - import_tasks: tasks/sublime-text.yml
      tags: [config, sublime-text]
    - import_tasks: tasks/services.yml
      tags: config
    - import_tasks: tasks/vim.yml
      tags: [config, vim]
