---

- name: Ensure ZSH is installed.
  homebrew:
    name: zsh
    state: latest

- name: Register homebrewed ZSH as globally available shell.
  become: yes
  lineinfile:
    dest: '/etc/shells'
    line: "/usr/local/bin/zsh"

- set_fact:
    local_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

- name: Set ZSH as shell for {{ local_user }}.
  become: yes
  user:
    name: "{{ local_user }}"
    shell: /usr/local/bin/zsh
