---

- name: Show extension warning ({{ finder_show_file_extensions_warning }})
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ finder_show_file_extensions_warning|bool }}"
  notify: Restart Finder

- name: Warn before emptying the trash ({{ finder_warn_before_emptying_the_trash }})
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: "{{ finder_warn_before_emptying_the_trash|bool }}"
  notify: Restart Finder

- name: Show All Files ({{ finder_show_all_files }})
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: "{{ finder_show_all_files|bool }}"
  notify: Restart Finder

- name: Keep folders on top when sorting by name ({{ finder_keep_folders_on_top }})
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: "{{ finder_keep_folders_on_top|bool }}"
  notify: Restart Finder

- name: Show full path in finder titlebar ({{ finder_show_full_path_in_titlebar }})
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: "{{ finder_show_full_path_in_titlebar|bool }}"
  notify: Restart Finder

- name: Show pathbar in bottom of finder ({{ finder_show_pathbar }})
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "{{ finder_show_pathbar|bool }}"
  notify: Restart Finder

- name: Show statusbar ({{ finder_show_statusbar }})
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "{{ finder_show_statusbar|bool }}"
  notify: Restart Finder

- name: When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
  notify: Restart Finder

- name: Enable quit menu item ({{ finder_enable_quit_menu_item }})
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: "{{ finder_enable_quit_menu_item|bool }}"
  notify: Restart Finder

- name: Default view style ({{ finder_default_view_style }})
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "{{ finder_default_view_style }}"
  notify: Restart Finder

- name: Show external harddrives on desktop ({{ finder_show_external_harddrives_on_desktop }})
  osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: "{{ finder_show_external_harddrives_on_desktop|bool }}"
  notify: Restart Finder

- name: Show harddrives on desktop ({{ finder_show_harddrives_on_desktop }})
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: "{{ finder_show_harddrives_on_desktop|bool }}"
  notify: Restart Finder

- name: Show mounted servers on desktop ({{ finder_show_mounted_servers_on_desktop }})
  osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: "{{ finder_show_mounted_servers_on_desktop|bool }}"
  notify: Restart Finder

- name: Show removable media on desktop ({{ finder_show_removable_media_on_desktop }})
  osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: "{{ finder_show_removable_media_on_desktop|bool }}"
  notify: Restart Finder

- name: Unhide user library folder
  command: chflags nohidden ~/Library/
  notify: Restart Finder

- name: Unhide system volumes folder
  command: chflags nohidden /Volumes
  become: true
  notify: Restart Finder

- name: Show item info near icons on the desktop and in other icon views ({{ finder_iconview_show_item_info }})
  command: /usr/libexec/PlistBuddy -c "Set :{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "DesktopViewSettings:IconViewSettings:showItemInfo {{ finder_iconview_show_item_info|bool }}"
    - "StandardViewSettings:IconViewSettings:showItemInfo {{ finder_iconview_show_item_info|bool }}"
  notify: Restart Finder

- name: Show item info to the right of the icons on the desktop ({{ finder_iconview_show_label_on_bottom }})
  command: /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom {{ finder_iconview_show_label_on_bottom|bool }}" ~/Library/Preferences/com.apple.finder.plist
  notify: Restart Finder

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
  notify: Restart Finder

- name: Increase grid spacing for icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
    - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
  notify: Restart Finder

- name: Increase the size of icons on the desktop and in other icon views
  command: "{{ item }}"
  with_items:
    - /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
    - /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
  notify: Restart Finder



#defaults write com.apple.finder XtraFinder_XFNewTerminalActionPlugin -bool true
#defaults write com.apple.finder XtraFinder_XFNewTerminalActionPlugin_TerminalApp -int 1
#defaults write com.apple.finder XtraFinder_XFNewFileActionPlugin -bool true
#defaults write com.apple.finder XtraFinder_XFSpringLoadedPathBarPlugin -bool true
#defaults write com.apple.finder XtraFinder_XFCopyQueuePlugin -bool true
#defaults write com.apple.finder XtraFinder_XFCutAndPastePlugin -bool true
#defaults write com.apple.finder XtraFinder_XFCopyPathMenuPlugin -bool true
#defaults write com.apple.finder XtraFinder_XFCopyPathMenuPlugin_Default -int 4
