---

- name: Disable Dashboard ({{ system_disable_dashboard }})
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: "{{ system_disable_dashboard|bool }}"

- name: Enable auto correct ({{ system_enable_auto_correct }})
  osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: "{{ system_enable_auto_correct|bool }}"

- name: Enable smart quotes ({{ system_enable_smart_quotes }})
  osx_defaults:
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: "{{ system_enable_smart_quotes|bool }}"

- name: Enable smart dashes ({{ system_enable_smart_dashes }})
  osx_defaults:
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: "{{ system_enable_smart_dashes|bool }}"

- name: Enable automatic capitalization ({{ system_enable_automatic_capitalization }})
  osx_defaults:
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: "{{ system_enable_automatic_capitalization|bool }}"

- name: Save application states on quit ({{ system_save_application_state_on_quit }})
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: "{{ system_save_application_state_on_quit|bool }}"

- name: Expand save panel by default ({{ system_expand_save_panel_by_default }})
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "{{ system_expand_save_panel_by_default|bool }}"
  notify: Restart Finder

- name: Expand print panel by default ({{ system_expand_print_panel_by_default }})
  osx_defaults:
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: "{{ system_expand_print_panel_by_default|bool }}"
  notify: Restart Finder

- name: Enable spring loading for directories ({{ system_enable_springloading_directories }})
  osx_defaults:
    key: com.apple.springing.enabled
    type: bool
    value: "{{ system_enable_springloading_directories|bool }}"

- name: Set delay for spring loading directories ({{ system_springloading_directories_delay }})
  osx_defaults:
    key: com.apple.springing.delay
    type: float
    value: "{{ system_springloading_directories_delay }}"

- name: Disable creating .DS_Store files on network shares ({{ system_disable_dsstore_on_network_shares }})
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: "{{ system_disable_dsstore_on_network_shares|bool }}"

- name: Disable creating .DS_Store files on usb drives ({{ system_disable_dsstore_on_usb_drives }})
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: "{{ system_disable_dsstore_on_usb_drives|bool }}"

- name: Disable disk image verification ({{ system_disable_disk_image_verification }})
  osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: "{{ item }}"
    type: bool
    value: "{{ system_disable_disk_image_verification|bool }}"
  with_items:
    - skip-verify
    - skip-verify-locked
    - skip-verify-remote

- name: Set action for double click on titlebar ({{ system_doubleclick_on_titlebar_action }})
  osx_defaults:
    key: AppleActionOnDoubleClick
    type: string
    value: "{{ system_doubleclick_on_titlebar_action }}"

- name: Set interface style ({{ system_interface_style }})
  osx_defaults:
    key: AppleInterfaceStyle
    type: string
    value: "{{ system_interface_style }}"

- name: Enable full keyboard access for all controls #(e.g. enable Tab in modal dialogs)
  osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 3   

- name: Enable subpixel font rendering on non-Apple LCDs # Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
  osx_defaults:
    key: AppleFontSmoothing
    type: int
    value: 1 



# enable ssh
#sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

# copy only mailadress to clipboard in mail
#defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# textedit use plaintext as default 
#defaults write com.apple.TextEdit RichText -int 0

# Disable the “Are you sure you want to open this application?” dialog
#defaults write com.apple.LaunchServices LSQuarantine -bool false

# Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
#/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local
