---

system:
  hostname: 
    computername: mh-mbp
    hostname: mh-mbp
    localhostname: mh-mbp  
  ui:
    interface_style: "Dark"
    expand_save_panel: yes
    expand_print_panel: yes
    titlebar_doubleclick_action: "Minimize"
    enable_subpixel_font_rendering: yes
    enable_focus_ring: no
    show_all_file_extensions: yes
    disable_dashboard: yes
    enable_springloading_directories: yes
    springloading_directories_delay: 2
    window_resize_speed: 0.001
    enable_opening_closing_window_animations: no
  screensaver:
    activation_delay: 300
    ask_password: yes
    ask_password_delay: 0
    screensaver:
      name: Fliqlo
      path: /Users/{{ ansible_user }}/Library/Screen Savers/Fliqlo.saver
  input:
    enable_auto_correct: no
    enable_smart_quotes: no
    enable_smart_dashes: no
    enable_automatic_capitalization: no
    enable_automatic_periods: no
    enable_continuous_spell_checking: no
    key_repeat_rate: 2
    initial_key_repeat_delay: 22
    enable_full_keyboard_access: yes
    enable_press_and_hold: no
    enable_space_hotkeys: yes
  security:
    enable_gatekeeper: no
    enable_quarantine: no
  misc:
    save_application_state_on_quit: yes
    disable_dsstore_on_network_shares: yes
    disable_dsstore_on_usb_drives: yes
    disable_disk_image_verification: yes
    disable_spotlight_network_indexing: yes
    save_new_docs_to_icloud: no
    enable_ssh: yes
    enable_crash_reporter: no
    enable_startup_sound: no
    enable_sudden_motion_sensor: yes
    enable_hibernation: no
  default_applications:
    # Iina
    - { extension: avi, handler: com.colliderli.iina }
    - { extension: flv, handler: com.colliderli.iina }
    - { extension: mkv, handler: com.colliderli.iina }
    - { extension: mov, handler: com.colliderli.iina }
    - { extension: mp4, handler: com.colliderli.iina }
    - { extension: mpg, handler: com.colliderli.iina }
    # MacDown
    - { extension: md, handler: com.uranusjr.macdown }
    # Sublime Text
    - { extension: cfg, handler: com.sublimetext.3 }
    - { extension: css, handler: com.sublimetext.3 }
    - { extension: inc, handler: com.sublimetext.3 }
    - { extension: js, handler: com.sublimetext.3 }
    - { extension: json, handler: com.sublimetext.3 }
    - { extension: php, handler: com.sublimetext.3 }
    - { extension: scss, handler: com.sublimetext.3 }
    - { extension: txt, handler: com.sublimetext.3 }
    - { extension: yml, handler: com.sublimetext.3 }

finder:
  new_window_target: "PfHm"
  show_file_extensions_warning: no
  warn_before_emptying_the_trash: no
  show_all_files: yes
  keep_folders_on_top: yes
  show_full_path_in_titlebar: yes
  show_pathbar: yes
  show_statusbar: yes
  enable_quit_menu_item: yes
  default_view_style: "clmv"
  show_external_harddrives_on_desktop: yes
  show_harddrives_on_desktop: yes
  show_mounted_servers_on_desktop: yes
  show_removable_media_on_desktop: yes
  iconview_show_item_info: yes
  iconview_show_label_on_bottom: no
  hide_user_library: no
  hide_system_volumes: no
  expand_infopane: 
    - { name: General , value: yes }
    - { name: MetaData , value: yes }
    - { name: OpenWith , value: yes }
    - { name: Name , value: yes }  
    - { name: Comments , value: yes }
    - { name: Preview , value: yes }
    - { name: Privileges , value: yes }
  iconview_arrange_by: "grid"
  iconview_grid_spacing: 60
  iconview_icon_size: 50
  enable_quicklook_text_selection: yes
  disable_all_animations: yes


dock:
  tile_size: 50
  show_idicator_lights: yes
  hidden_items_translucent: yes
  fade_in_time: 0
  rearrange_spaces_by_last_use: no
  autohide: yes
  apps:
    - name: Reeder
      path: /Applications/Reeder.app
    - name: Safari
      path: /Applications/Safari.app
    - name: iTunes
      path: /Applications/iTunes.app
    - name: Mail
      path: /Applications/Mail.app   
    - name: Erinnerungen
      path: /Applications/Reminders.app
    - name: iStudiez Pro
      path: /Applications/iStudiez Pro.app
    - name: Fantastical 2
      path: /Applications/Fantastical 2.app
    - name: Evernote
      path: /Applications/Evernote.app
    - name: Franz
      path: /Applications/Franz.app
    - name: Nachrichten
      path: /Applications/Messages.app
    - name: iTerm
      path: /Applications/iTerm.app
    - name: Tower
      path: /Applications/Tower.app
    - name: Sublime Text
      path: /Applications/Sublime Text.app
    - name: Transmit
      path: /Applications/Transmit.app
    - name: Mathematica
      path: /Applications/Mathematica.app
    - name: Parallels Desktop
      path: /Applications/Parallels Desktop.app
    - name: Remote Desktop
      path: /Applications/Microsoft Remote Desktop.app 
  spacers:
    - after: iTunes
    - after: Nachrichten


safari:
  show_full_url_in_address_bar: yes
  open_safe_files_automatically: no
  enable_status_bar: yes
  enable_developer_menu: yes
  autofill_passwords: no
  show_favorites_bar: yes
  disable_thumbnail_cache: yes
  search_with_word_start_only: no


mail:
  address_include_name_on_pasteboard: no


textedit:
  default_doc_plaintext: yes


terminal:
  enable_secure_keyboard_entry: no


















iterm2_enable_automatic_updates: true
iterm2_preference_folder: "{{ playbook_dir }}/files"

## yadm
dotfiles_repo_url: 'https://github.com/KingLoui/dotfiles.git'

