---

- name: "Show full URL in the address bar ({{ show_full_url_in_address_bar }})"
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: ShowFullURLInSmartSearchField
    type: bool
    value: "{{ show_full_url_in_address_bar }}"
  notify: Restart Safari

- name: "Open 'safe' files automatically ({{ open_safe_files_automatically }})"
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: AutoOpenSafeDownloads
    type: bool
    value: "{{ open_safe_files_automatically }}"
  notify: Restart Safari

- name: "Show status bar ({{ show_status_bar }})"
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: ShowOverlayStatusBar
    type: bool
    value: "{{ show_status_bar }}"
  notify: Restart Safari

- name: "Show status bar ({{ show_developer_menu }})"
  osx_defaults:
    domain: "{{ safari_defaults_domain }}"
    key: IncludeDevelopMenu
    type: bool
    value: "{{ show_developer_menu|bool }}"
  notify: Restart Safari
