---
- import_tasks: finder.yml
  tags: [finder]

- import_tasks: dock.yml
  tags: [dock]

- import_tasks: screensaver.yml
  tags: [screensaver]

- import_tasks: performance.yml
  tags: [performance]

- import_tasks: hostname.yml
  tags: [hostname]

- import_tasks: system.yml
  tags: [misc]
