---

- name: Save application states on quit ({{ save_application_state_on_quit }})
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: "{{ save_application_state_on_quit|bool }}"

- name: Expand save panel by default ({{ expand_save_panel_by_default }})
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "{{ expand_save_panel_by_default|bool }}"
  notify: Restart Finder

- name: Expand print panel by default ({{ expand_print_panel_by_default }})
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: "{{ expand_print_panel_by_default|bool }}"
  notify: Restart Finder

- name: Show extension warning ({{ show_file_extensions_warning }})
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ show_file_extensions_warning|bool }}"
  notify: Restart Finder

- name: Warn before emptying the trash ({{ warn_before_emptying_the_trash }})
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: "{{ warn_before_emptying_the_trash|bool }}"
  notify: Restart Finder



