---

- name: Ensure Homebrew Taps.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - caskroom/cask
    - caskroom/drivers
    - caskroom/fonts
    - buo/cask-upgrade

- name: Install homebrew apps.
  homebrew:
    name: "{{ item }}"
  with_items:
    - youtube-dl

- name: Install casks.
  homebrew_cask:
    name: "{{ item }}"
  with_items:
    - dash
    - firefox
    - font-fira-code
    - font-roboto
    - font-roboto-condensed
    - font-roboto-mono
    - google-chrome
    - iterm2
    - java
    - sequel-pro
    - slack
    - spotify
    - sublime-text
    - tower
    - vlc
    - whatsapp

- include_role:
    name: mas
  tags: [mas]
  vars:
    mas_apps:
      - { name: iStudiezPro, id: 402989379 }
      - { name: Keynote, id: 409183694 }
      - { name: LastPass, id: 926036361 }
      - { name: MSRemoteDesktop, id: 715768417 }
      - { name: Numbers, id: 409203825 }
      - { name: Pages, id: 409201541 }
      - { name: Reeder, id: 880001334 }
      - { name: RemoteWakeUp, id: 860874272 }
      - { name: Xcode, id: 497799835 }
    mas_upgrade_all_apps: yes

- include_role:
    name: settings/dock
  tags: [settings-dock]
  vars:
    dock_remove_undefined: yes
    dock_apps:
      - name: Fantastical 2
        path: /Applications/Fantastical 2.app
      - name: Slack
        path: /Applications/Slack.app
      - name: Nachrichten
        path: /Applications/Messages.app
      - name: Safari
        path: /Applications/Safari.app
      - name: Google Chrome
        path: /Applications/Google Chrome.app
      - name: Sublime Text
        path: /Applications/Sublime Text.app
      - name: Spotify
        path: /Applications/Spotify.app
      - name: iTerm
        path: /Applications/iTerm.app
